apiVersion: v1
kind: Service
metadata:
  name: {{ include "hydroxide.fullname" . }}
  labels:
    {{- include "hydroxide.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.tls.enabled }}
    {{- if .Values.tls.imaps.enabled }}
    - port: {{ .Values.tls.imaps.servicePort }}
      targetPort: imaps
      protocol: TCP
      name: imaps
    {{- end }}
    {{- if .Values.tls.smtps.enabled }}
    - port: {{ .Values.tls.smtps.servicePort }}
      targetPort: smtps
      protocol: TCP
      name: smtps
    {{- end }}
    {{- else }}
    - port: {{ .Values.service.imapPort }}
      targetPort: imap
      protocol: TCP
      name: imap
    - port: {{ .Values.service.smtpPort }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    {{- end }}
    - port: {{ .Values.service.carddavPort }}
      targetPort: carddav
      protocol: TCP
      name: carddav
  selector:
    {{- include "hydroxide.selectorLabels" . | nindent 4 }}
