image:
  repository: ghcr.io/random-typ/hydroxide-captcha-fix
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  imapPort: 1143
  smtpPort: 1025
  carddavPort: 8080

tls:
  enabled: false
  image:
    repository: docker.io/stunnel/stunnel
    tag: latest
    pullPolicy: IfNotPresent
  # Name of a kubernetes.io/tls Secret containing tls.crt and tls.key.
  certificateSecretName: ""
  imaps:
    enabled: true
    servicePort: 993
    containerPort: 1993
  smtps:
    enabled: true
    servicePort: 465
    containerPort: 1465
  resources: {}

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
