foreground = yes
pid =

[imaps]
accept = 0.0.0.0:1993
connect = hydroxide:1143
cert = /certs/tls.crt
key = /certs/tls.key

[smtps]
accept = 0.0.0.0:1465
connect = hydroxide:1025
cert = /certs/tls.crt
key = /certs/tls.key
